### ISSUE TITLE
Variable support_email in error_extra.html contains empty value

### ISSUE THREAD

**Issue by michaelwood** [OpenDataServices/lib-cove-web#101]
`support_email` appears to be correctly configured in COVE_CONFIG but the value does not appear to be passed back in the context.

https://github.com/OpenDataServices/lib-cove-web/blob/main/cove/templates/error_extra.html

Reproduce: 
- Attempt to test a invalid json document.

Tested on oc4ids and threesixtygiving's cove.

**Comment by jpmckinney** [comment]
This issue is now closed @odscjames @Bjwebb
