### ISSUE TITLE
How to pass options from input page to results page.

### ISSUE THREAD

**Issue by michaelwood** [OpenDataServices/lib-cove-web#102]
I have a need in 360Giving's cove to be able to pass a custom parameter through to the results (explore) page.

Currently the data input page / form is rendered by 
```python
def data_input(request, form_classes=default_form_classes, text_file_name='test.json') 
#...
``` 
https://github.com/OpenDataServices/lib-cove-web/blob/main/cove/input/views.py#L90

in input/views.

When it receives the POST/GET from the forms on the input page it goes down a different path to a redirect:

```
           return redirect(data.get_absolute_url())
```

This means that any custom form data (in my case a ``` <input type="hidden" ...>``` doesn't get kept.

https://github.com/OpenDataServices/lib-cove-web/blob/main/cove/input/views.py#L88

Does (@Bjwebb @odscjames @rhiaro @BibianaC @Lathrisk ) anyone have an idea around this (other than using a cookie) or would a patch to that function to store the  `request_data`  in say, a new field in SuppliedData ? or maybe append the GET params to the redirect?...

**Comment by Bjwebb** [comment]
SuppliedData objects are kept indefinitely, so that we can calculate stats. Is the extra field you're adding appropriate/useful for that? Is so, I'd add it there. Otherwise I'd pass it on as a GET param.

How custom is your custom field? I'm generally quite happy with adding it to this library, as it only exists for our convenience really.

**Comment by michaelwood** [comment]
@Bjwebb ah I'm using SuppliedData slightly differently as I need to store the status of results for retrieval later on and I'm doing that by adding a FK in my cove_360 model...

The field is pretty custom... it is to provide a flag in the explore page that the supplied url is intended to be published after checking.

version here: with "Check and Publish 360Giving data" http://dqt.360dev1.vs.mythic-beasts.com/ 

The issue I have is that I need to toggle the "results passed - you can now publish" button on the results page depending on whether the form was submitted via the "Check and Publish" instead of the normal check ( I have an `<input type="hidden" name="self_publishing" value="true">` added to that form, but that param gets lost after redirect )

**Comment by michaelwood** [comment]
> @Bjwebb ah I'm using SuppliedData slightly differently as I need to store the status of results for retrieval later on and I'm doing that by adding a FK in my cove_360 model...

https://github.com/ThreeSixtyGiving/dataquality/blob/automated-registry/cove/cove_360/models.py
