### ISSUE TITLE
Make is so T&C details are customisable in direct app

### ISSUE THREAD

**Issue by ghost** [OpenDataServices/lib-cove-web#28]
We just had https://github.com/OpenDataServices/lib-cove-web/pull/26 and there is nothing wrong with that pull request as it stands BUT it is daft that we had to do it in this repo at all.

Details like the address should just be in the main Cove app repo, and we should not be relying on the app variable to distinguish between them - we can't trust that is always set.

Instead, I'd suggest one of 2 solutions:

1) We remove terms from this library totally, and make every app have it's own terms template. This has the benefit of allowing each app to have totally different custom terms. 

However, we probably want to have a lot of content in custom between each app, so that might count as unnecessary duplication.

2) Have a base terms template in this library with a separate block for each bit. Any bit that a app might want to change has it's own block. eg

```

{% block content_terms_intro %}
<p>
    This web application is free software designed to help people check data published to the Standard.</p>
{% endblock %}
{% block content_terms_warranty %}
  <p>It is offered as service WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.</p>
{% endblock %}
```

Then an upstream app can have it's own template that extends this base, but overwrite any block it wants - for instance, every app will want to overwrite content_terms_intro, but probably none will want to overwrite content_terms_warranty.

**Comment by robredpath** [comment]
👍

**Comment by jpmckinney** [comment]
@Bjwebb This issue is already resolved. (There are now 22 terms_* templates.) Please close to keep tracker tidy.
