### ISSUE TITLE
Packages uploaded to PyPi are missing files!

### ISSUE THREAD

**Issue by ghost** [OpenDataServices/lib-cove-web#38]

**Comment by jpmckinney** [comment]
This seems to be fixed. Note that using `check-manifest -c` to create a `MANIFEST.in` file and then running `check-manifest` in CI is much easier than maintaining `package_data`.

**Comment by jpmckinney** [comment]
@Bjwebb This issue is already resolved. (`package_data` was updated.) Please close to keep tracker tidy.
