### ISSUE TITLE
cove/templatetags/cove_tags.py tries to use unknown variable e_instance

### ISSUE THREAD

**Issue by ghost** [OpenDataServices/lib-cove-web#66]
https://github.com/OpenDataServices/lib-cove-web/blob/main/cove/templatetags/cove_tags.py#L159

(Found when trying to apply Flake8)

**Comment by Bjwebb** [comment]
Sentry issue: [COVE-OCDS-3V](https://sentry.io/organizations/open-contracting-partnership/issues/2095738724/?referrer=github_integration)
