### ISSUE TITLE
e_instance variable doesn't exist

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/lib-cove-web#70]
The line that uses it was introduced in #58 cc @Bjwebb

**Comment by Bjwebb** [comment]
I think this should be fixed now due to https://github.com/OpenDataServices/lib-cove-web/pull/68, which is included in the release cove-ocds uses, but not cove-oc4ids.

**Comment by Bjwebb** [comment]
(edited to link to [correct PR](https://github.com/OpenDataServices/lib-cove-web/pull/68))

**Comment by jpmckinney** [comment]
Indeed - I forgot to pull from my local repo.
