### ISSUE TITLE
okfnlabs have archived their datapipes CSV viewer, so codelist links using it break

### ISSUE THREAD

**Issue by pindec** [OpenDataServices/lib-cove-web#74]
Links now redirected to an archive page.

Source of error in [templates/additional_codelist_values.html](https://github.com/OpenDataServices/lib-cove-web/blob/c242d507da948059520a97248041035f18a04e21/cove/templates/additional_codelist_values.html#L18).
       
`<a href="http://datapipes.okfnlabs.org/csv/html/?url={{detail.codelist_url}}" >{{detail.codelist}}</a>`

Currently affecting [OCDS DRT](https://github.com/open-contracting/cove-ocds/issues/152).

**Comment by kindly** [comment]
Looked into alternative services that do this and can't find any.

Just tried hosting this ourselves on digital ocean apps and it worked without hitch i.e

https://datapipes-k55ba.ondigitalocean.app/csv/html/?url=https://raw.githubusercontent.com/open-contracting/standard/1.1/schema/codelists/releaseTag.csv

otherwise it means we need to write a csv viewer into cove which would take some time.

It means $5 a month on do or $7 on heroku.

**Comment by kindly** [comment]
Made heroku app instead.

http://datapipes.herokuapp.com/csv/html/?url=https://raw.githubusercontent.com/open-contracting/standard/1.1/schema/codelists/releaseTag.csv

and made a pull request linking to new service.

**Comment by jpmckinney** [comment]
This seems to be fixed by #75

**Comment by jpmckinney** [comment]
Looks like ODS shut down this service? @duncandewhurst

**Comment by jpmckinney** [comment]
The additional_codelist_values.html template still uses http://datapipes.herokuapp.com

This issue can be reopened.

**Comment by duncandewhurst** [comment]
> Looks like ODS shut down this service? @duncandewhurst

@Bjwebb do you know what happened to the datapipes heroku app?

**Comment by ghost** [comment]
The latest source code seems to be https://github.com/datopian/datapipes

I can't find a fork for us, so I assume we installed the main code?

In the long run, we want to be writing out this dependency - we don't want to be relying on an app that was deprecated in Dec 2020 (tho oddly, Rufus did merge a version bump in Jan 2022 but I wouldn't trust how tested that was so even more iffy)

In the short term, putting this or something else up may be the quick option.

Does anyone know, do we have any user requirements about what users should see when they click that link? Is it just the contents of that CSV in a nice table, or is there more?

**Comment by ghost** [comment]
For reference http://datapipes.herokuapp.com/ was removed Aug 2022

**Comment by michaelwood** [comment]
Replaced in 360Giving's cove - https://github.com/ThreeSixtyGiving/dataquality/commit/9df703b6d36a2688630e133e79bc2247c687723b This is effectively overriding that particular template from lib-cove-web.

**Comment by jpmckinney** [comment]
Happy for this to be resolved like 360’s solution.

**Comment by ghost** [comment]
That might be the best way - I can remove the link from the base template, then we'll let individual apps overwrite the template.

**Comment by jpmckinney** [comment]
It might make sense to do what 360 did in the base template, so that there is no loss of functionality.

**Comment by ghost** [comment]
Well, it's an unusual situation in that the functionality has been lost for a year anyway. (Normally with library code, apps can avoid the breakage by staying on an older version but not this time). That gives us some flexibility in thinking about the fastest solution.

To do library code for this we'll have to review where each standard that used this wanted to link to and make sure the library code we put in was flexible enough to accommodate that, in terms of how it constructs URLs.  

It may be faster to get fixes live if we just let individual apps put in their own work. Maybe we remove the broken link now so at least users don't follow broken links, then we come back to thinking about library code later if there is demand for it.

We can ask users of this library to link to any fixes they put in here, which will help review if there is library code we can do later.

**Comment by jpmckinney** [comment]
Up to you. In that case, could you make a PR on cove-ocds?

**Comment by ghost** [comment]
libcoveweb 0.30 released

**Comment by jpmckinney** [comment]
This issue is resolved and can be closed. Thank you!

**Comment by ghost** [comment]
Is there also the OC4IDS cove?

**Comment by jpmckinney** [comment]
Good catch, yes: https://github.com/open-contracting/cove-oc4ids

**Comment by jpmckinney** [comment]
This is also closed @odscjames @Bjwebb
