### ISSUE TITLE
Remove django-environ dependency

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/lib-cove-web#80]
Right now, all CoVE apps import settings.py from this package.

django-environ isn't really maintained (lots of issues and PRs without responses), and it is doing very little that can't be done with python-dotenv (which has no dependencies) and a bit of plain Python code.

**Comment by sergeyklay** [comment]
May I suggest [django-environ-2](https://github.com/sergeyklay/django-environ-2) instead?  django-environ-2 was forked from the [django-environ](https://github.com/joke2k/django-environ) initially written by [Daniele Faraglia](https://github.com/joke2k) to breathe new life into it and set a more dynamic pace of development. It’s rigorously tested on Python 3.6+, and officially supports Django 1.11, 2.2, 3.0, 3.1 and 3.2.

**Comment by jpmckinney** [comment]
Closed by #126
